### ISSUE TITLE
Unable to handle model evidence > 1?

### ISSUE THREAD

**Issue by Losses** [mattelisi/bmsR#1]
I don't know if i misunderstood something, but sometimes model evidence may greater than 1, in this situation, the package can't work properly.

I got the following warning message: 

```
Warning message:
In xp + unname(tapply(j, factor(j), length)) :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
```

and the result is strange:

```
$alpha
[1] 44.062318  1.234421  1.234421  1.234421  1.234421

$r
[1] 0.89923097 0.02519226 0.02519226 0.02519226 0.02519226

$xp
[1] 1 1 1 1 1

$bor
o5a 
NaN 

$pxp
[1] NaN NaN NaN NaN NaN
```

**Comment by mattelisi** [comment]
Hi, the model evidence should never be higher than 1 by definition, since it is a probability - it should be the [marginal likelihood](https://en.wikipedia.org/wiki/Marginal_likelihood) of the data, or some approximation of it. (Note that the function take the log of the model evidences as input, which should be negative values). I should probably add some checking of the input and some informative warning/error messages.
